package com.crm.client.po;

import java.util.Date;

/**
 * TClient generated by MyEclipse Persistence Tools
 */

public class TClient implements java.io.Serializable {

	// Fields

	private String phone;

	private String name;

	private String type;

	private String code;

	private Long provice;

	private Long city;

	private String room;

	private Date regdate;

	private String address;

	private Long grade;

	private Long area;

	private Long brand;

	private String linkman;

	private String isparty;

	private String isgroup;

	private String ischeck;

	private Date bigdate;
	
	private TClientinfo clientinfo; //客户信息

	private Long sascore;
	
	private Long endscore;
	
	private Long safee;
	
	private Long efee;
	
	// Constructors



	public Long getSafee() {
		return safee;
	}

	public void setSafee(Long safee) {
		this.safee = safee;
	}

	public Long getEndscore() {
		return endscore;
	}

	public void setEndscore(Long endscore) {
		this.endscore = endscore;
	}

	public Long getSascore() {
		return sascore;
	}

	public void setSascore(Long sascore) {
		this.sascore = sascore;
	}

	/** default constructor */
	public TClient() {
	}

	/** full constructor */
	public TClient(String name, String type, String code, Long provice,
			Long city, String room, Date regdate, String address, Long grade,
			Long area, Long brand, String linkman, String isparty,
			String isgroup, String ischeck, Date bigdate) {
		this.name = name;
		this.type = type;
		this.code = code;
		this.provice = provice;
		this.city = city;
		this.room = room;
		this.regdate = regdate;
		this.address = address;
		this.grade = grade;
		this.area = area;
		this.brand = brand;
		this.linkman = linkman;
		this.isparty = isparty;
		this.isgroup = isgroup;
		this.ischeck = ischeck;
		this.bigdate = bigdate;
	}

	// Property accessors

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Long getProvice() {
		return this.provice;
	}

	public void setProvice(Long provice) {
		this.provice = provice;
	}

	public Long getCity() {
		return this.city;
	}

	public void setCity(Long city) {
		this.city = city;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public Date getRegdate() {
		return this.regdate;
	}

	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Long getGrade() {
		return this.grade;
	}

	public void setGrade(Long grade) {
		this.grade = grade;
	}

	public Long getArea() {
		return this.area;
	}

	public void setArea(Long area) {
		this.area = area;
	}

	public Long getBrand() {
		return this.brand;
	}

	public void setBrand(Long brand) {
		this.brand = brand;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getIsparty() {
		return this.isparty;
	}

	public void setIsparty(String isparty) {
		this.isparty = isparty;
	}

	public String getIsgroup() {
		return this.isgroup;
	}

	public void setIsgroup(String isgroup) {
		this.isgroup = isgroup;
	}

	public String getIscheck() {
		return this.ischeck;
	}

	public void setIscheck(String ischeck) {
		this.ischeck = ischeck;
	}

	public Date getBigdate() {
		return this.bigdate;
	}

	public void setBigdate(Date bigdate) {
		this.bigdate = bigdate;
	}

	public TClientinfo getClientinfo() {
		return clientinfo;
	}

	public void setClientinfo(TClientinfo clientinfo) {
		this.clientinfo = clientinfo;
	}

	public Long getEfee() {
		return efee;
	}

	public void setEfee(Long efee) {
		this.efee = efee;
	}
}