package com.crm.client.po;

/**
 * TOperationtype generated by MyEclipse Persistence Tools
 */

public class TOperationtype implements java.io.Serializable {

	// Fields

	private Long id;

	private String type;

	private Long pid;
	
	private String remind;

	// Constructors

	/** default constructor */
	public TOperationtype() {
	}

	/** full constructor */
	public TOperationtype(String type, Long pid,String remind) {
		this.type = type;
		this.pid = pid;
		this.remind = remind;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	public String getRemind() {
		return remind;
	}

	public void setRemind(String remind) {
		this.remind = remind;
	}

}