package com.crm.client.po;

import java.util.Date;

/**
 * TOperlog generated by MyEclipse Persistence Tools
 */

public class TOperlog implements java.io.Serializable {

	// Fields

	private Long id;

	private Long operid;

	private String oldstate;

	private String newstate;

	private String changeuser;

	private Date regdate;

	private String result;

	// Constructors

	/** default constructor */
	public TOperlog() {
	}

	/** full constructor */
	public TOperlog(Long operid, String oldstate, String newstate,
			String changeuser, Date regdate, String result) {
		this.operid = operid;
		this.oldstate = oldstate;
		this.newstate = newstate;
		this.changeuser = changeuser;
		this.regdate = regdate;
		this.result = result;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getOperid() {
		return this.operid;
	}

	public void setOperid(Long operid) {
		this.operid = operid;
	}

	public String getOldstate() {
		return this.oldstate;
	}

	public void setOldstate(String oldstate) {
		this.oldstate = oldstate;
	}

	public String getNewstate() {
		return this.newstate;
	}

	public void setNewstate(String newstate) {
		this.newstate = newstate;
	}

	public String getChangeuser() {
		return this.changeuser;
	}

	public void setChangeuser(String changeuser) {
		this.changeuser = changeuser;
	}

	public Date getRegdate() {
		return this.regdate;
	}

	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}