package com.crm.client.po;

import java.util.Date;

/**
 * TRulelog generated by MyEclipse Persistence Tools
 */

public class TRulelog implements java.io.Serializable {

	// Fields

	private Long id;

	private Long ruleid;

	private String creater;

	private Date createdate;

	private String operator;

	private Date operdate;

	private String opertype;

	// Constructors

	/** default constructor */
	public TRulelog() {
	}

	/** full constructor */
	public TRulelog(Long ruleid, String creater, Date createdate,
			String operator, Date operdate, String opertype) {
		this.ruleid = ruleid;
		this.creater = creater;
		this.createdate = createdate;
		this.operator = operator;
		this.operdate = operdate;
		this.opertype = opertype;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getRuleid() {
		return this.ruleid;
	}

	public void setRuleid(Long ruleid) {
		this.ruleid = ruleid;
	}

	public String getCreater() {
		return this.creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Date getOperdate() {
		return this.operdate;
	}

	public void setOperdate(Date operdate) {
		this.operdate = operdate;
	}

	public String getOpertype() {
		return this.opertype;
	}

	public void setOpertype(String opertype) {
		this.opertype = opertype;
	}

}