package com.crm.score.po;

import java.util.Date;

/**
 * TPresent generated by MyEclipse Persistence Tools
 */

public class TPresent implements java.io.Serializable {

	// Fields

	private Long id;

	private String name;

	private String ptype;

	private Long num;

	private String picture;

	private Long integral;

	private String del;

	private Date invalidate;

	private Date start;

	private Date end;
	
	private TChange change;

	// Constructors

	/** default constructor */
	public TPresent() {
	}

	/** full constructor */
	public TPresent(String name, String ptype, Long num, String picture,
			Long integral, String del, Date invalidate) {
		this.name = name;
		this.ptype = ptype;
		this.num = num;
		this.picture = picture;
		this.integral = integral;
		this.del = del;
		this.invalidate = invalidate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPtype() {
		return this.ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	public Long getNum() {
		return this.num;
	}

	public void setNum(Long num) {
		this.num = num;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Long getIntegral() {
		return this.integral;
	}

	public void setIntegral(Long integral) {
		this.integral = integral;
	}

	public String getDel() {
		return this.del;
	}

	public void setDel(String del) {
		this.del = del;
	}

	public Date getInvalidate() {
		return this.invalidate;
	}

	public void setInvalidate(Date invalidate) {
		this.invalidate = invalidate;
	}

	public Date getEnd() {
		return end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public Date getStart() {
		return start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public TChange getChange() {
		return change;
	}

	public void setChange(TChange change) {
		this.change = change;
	}

}