package com.crm.club.po;

/**
 * UnionBinfo generated by MyEclipse Persistence Tools
 */

public class UnionBinfo implements java.io.Serializable {

	// Fields

	private Long unionbId;//商家ID

	private String unionbType;//合作伙伴类型

	private String VLevel;//级别

	private String fullName;//全称

	private String shortName;//简称

	private String property;//性质

	private String unionbAddr;//地址

	private String workstatus;//经营状况

	private String corporation;//法人

	private String corSex;//性别

	private String corJobs;//职位

	private Long empCount;//员工数量

	private Long regmoney;//注册资金

	private String linkman;//联系人
	private String  tel;//联系方式

	private String islogout;//是否注销

	private String ischeck;//审核状况

	// Constructors

	/** default constructor */
	public UnionBinfo() {
	}

	/** full constructor */
	public UnionBinfo(String unionbType, String VLevel, String fullName,
			String shortName, String property, String unionbAddr,
			String workstatus, String corporation, String corSex,
			String corJobs, Long empCount, Long regmoney, String linkman,
			 String islogout, String ischeck,String tel) {
		this.unionbType = unionbType;
		this.VLevel = VLevel;
		this.fullName = fullName;
		this.shortName = shortName;
		this.property = property;
		this.unionbAddr = unionbAddr;
		this.workstatus = workstatus;
		this.corporation = corporation;
		this.corSex = corSex;
		this.corJobs = corJobs;
		this.empCount = empCount;
		this.regmoney = regmoney;
		this.linkman = linkman;
		this.tel=tel;
		this.islogout = islogout;
		this.ischeck = ischeck;
	}

	// Property accessors

	public Long getUnionbId() {
		return this.unionbId;
	}

	public void setUnionbId(Long unionbId) {
		this.unionbId = unionbId;
	}

	public String getUnionbType() {
		return this.unionbType;
	}

	public void setUnionbType(String unionbType) {
		this.unionbType = unionbType;
	}

	public String getVLevel() {
		return this.VLevel;
	}

	public void setVLevel(String VLevel) {
		this.VLevel = VLevel;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getProperty() {
		return this.property;
	}

	public void setProperty(String property) {
		this.property = property;
	}

	public String getUnionbAddr() {
		return this.unionbAddr;
	}

	public void setUnionbAddr(String unionbAddr) {
		this.unionbAddr = unionbAddr;
	}

	public String getWorkstatus() {
		return this.workstatus;
	}

	public void setWorkstatus(String workstatus) {
		this.workstatus = workstatus;
	}

	public String getCorporation() {
		return this.corporation;
	}

	public void setCorporation(String corporation) {
		this.corporation = corporation;
	}

	public String getCorSex() {
		return this.corSex;
	}

	public void setCorSex(String corSex) {
		this.corSex = corSex;
	}

	public String getCorJobs() {
		return this.corJobs;
	}

	public void setCorJobs(String corJobs) {
		this.corJobs = corJobs;
	}

	public Long getEmpCount() {
		return this.empCount;
	}

	public void setEmpCount(Long empCount) {
		this.empCount = empCount;
	}

	public Long getRegmoney() {
		return this.regmoney;
	}

	public void setRegmoney(Long regmoney) {
		this.regmoney = regmoney;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	
	public String getIslogout() {
		return this.islogout;
	}

	public void setIslogout(String islogout) {
		this.islogout = islogout;
	}

	public String getIscheck() {
		return this.ischeck;
	}

	public void setIscheck(String ischeck) {
		this.ischeck = ischeck;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

}