package com.crm.club.po;

/**
 * ClubNetInfo generated by MyEclipse Persistence Tools
 */

public class ClubNetInfo implements java.io.Serializable {

	// Fields

	private Long clubnetId;

	private String clubnetAddr;

	private String clubnetTelnum;

	private String clubnetManger;

	private Long clubnetType;

	private String clubnetConten;

	private Long clubnetLevel;

	private Long clubnetState;

	// Constructors

	/** default constructor */
	public ClubNetInfo() {
	}

	/** full constructor */
	public ClubNetInfo(String clubnetAddr, String clubnetTelnum,
			String clubnetManger, Long clubnetType, String clubnetConten,
			Long clubnetLevel, Long clubnetState) {
		this.clubnetAddr = clubnetAddr;
		this.clubnetTelnum = clubnetTelnum;
		this.clubnetManger = clubnetManger;
		this.clubnetType = clubnetType;
		this.clubnetConten = clubnetConten;
		this.clubnetLevel = clubnetLevel;
		this.clubnetState = clubnetState;
	}

	// Property accessors

	public Long getClubnetId() {
		return this.clubnetId;
	}

	public void setClubnetId(Long clubnetId) {
		this.clubnetId = clubnetId;
	}

	public String getClubnetAddr() {
		return this.clubnetAddr;
	}

	public void setClubnetAddr(String clubnetAddr) {
		this.clubnetAddr = clubnetAddr;
	}

	public String getClubnetTelnum() {
		return this.clubnetTelnum;
	}

	public void setClubnetTelnum(String clubnetTelnum) {
		this.clubnetTelnum = clubnetTelnum;
	}

	public String getClubnetManger() {
		return this.clubnetManger;
	}

	public void setClubnetManger(String clubnetManger) {
		this.clubnetManger = clubnetManger;
	}

	public Long getClubnetType() {
		return this.clubnetType;
	}

	public void setClubnetType(Long clubnetType) {
		this.clubnetType = clubnetType;
	}

	public String getClubnetConten() {
		return this.clubnetConten;
	}

	public void setClubnetConten(String clubnetConten) {
		this.clubnetConten = clubnetConten;
	}

	public Long getClubnetLevel() {
		return this.clubnetLevel;
	}

	public void setClubnetLevel(Long clubnetLevel) {
		this.clubnetLevel = clubnetLevel;
	}

	public Long getClubnetState() {
		return this.clubnetState;
	}

	public void setClubnetState(Long clubnetState) {
		this.clubnetState = clubnetState;
	}

}