package com.crm.score.po;

import java.util.Date;

/**
 * TBack generated by MyEclipse Persistence Tools
 */

public class TBack implements java.io.Serializable {

	// Fields

	private Long id;

	private String cid;

	private String phone;

	private Long prisentid;

	private Long backnum;

	private String operater;

	private Date bdate;

	// Constructors

	/** default constructor */
	public TBack() {
	}

	/** full constructor */
	public TBack(String cid, String phone, Long prisentid, Long backnum,
			String operater, Date bdate) {
		this.cid = cid;
		this.phone = phone;
		this.prisentid = prisentid;
		this.backnum = backnum;
		this.operater = operater;
		this.bdate = bdate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Long getPrisentid() {
		return this.prisentid;
	}

	public void setPrisentid(Long prisentid) {
		this.prisentid = prisentid;
	}

	public Long getBacknum() {
		return this.backnum;
	}

	public void setBacknum(Long backnum) {
		this.backnum = backnum;
	}

	public String getOperater() {
		return this.operater;
	}

	public void setOperater(String operater) {
		this.operater = operater;
	}

	public Date getBdate() {
		return this.bdate;
	}

	public void setBdate(Date bdate) {
		this.bdate = bdate;
	}

}