package com.crm.score.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TChange generated by MyEclipse Persistence Tools
 */

public class TChange implements java.io.Serializable {

	// Fields

	private String id;

	private String phone;

	private Long type;

	private Long changenum;

	private Long total;

	private String operater;

	private Date cdate;
	
	private Set<TChangeItem> items = new HashSet<TChangeItem>();

	private Long tostart;
	
	private Long toend;
	
	private String  pname;
	
	private Date startDate;
	
	private Date endDate;
	// Constructors

	public Long getToend() {
		return toend;
	}

	public void setToend(Long toend) {
		this.toend = toend;
	}

	public Long getTostart() {
		return tostart;
	}

	public void setTostart(Long tostart) {
		this.tostart = tostart;
	}

	/** default constructor */
	public TChange() {
	}

	/** full constructor */
	public TChange(String phone, Long type, Long changenum, Long total,
			String operater, Date cdate) {
		this.phone = phone;
		this.type = type;
		this.changenum = changenum;
		this.total = total;
		this.operater = operater;
		this.cdate = cdate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

	public Long getChangenum() {
		return this.changenum;
	}

	public void setChangenum(Long changenum) {
		this.changenum = changenum;
	}

	public Long getTotal() {
		return this.total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}

	public String getOperater() {
		return this.operater;
	}

	public void setOperater(String operater) {
		this.operater = operater;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public Set<TChangeItem> getItems() {
		return items;
	}

	public void setItems(Set<TChangeItem> items) {
		this.items = items;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

}