package com.crm.score.po;
/**
 * TMonthScore generated by MyEclipse Persistence Tools
 */

public class TMonthScore implements java.io.Serializable {

	// Fields

	private Long id;

	private String phone;

	private Long total;

	private String month;

	private Long pay;

	private Long basic;

	private Long power;

	private Long prize;

	private Long adjust;

	private Long change;
	
	private String sdate;
	
	private String edate;

	// Constructors

	/** default constructor */
	public TMonthScore() {
	}

	/** full constructor */
	public TMonthScore(String phone, Long total, String month, Long pay,
			Long basic, Long power, Long prize, Long adjust, Long change) {
		this.phone = phone;
		this.total = total;
		this.month = month;
		this.pay = pay;
		this.basic = basic;
		this.power = power;
		this.prize = prize;
		this.adjust = adjust;
		this.change = change;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Long getTotal() {
		return this.total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}

	public Long getPay() {
		return this.pay;
	}

	public void setPay(Long pay) {
		this.pay = pay;
	}

	public Long getBasic() {
		return this.basic;
	}

	public void setBasic(Long basic) {
		this.basic = basic;
	}

	public Long getPower() {
		return this.power;
	}

	public void setPower(Long power) {
		this.power = power;
	}

	public Long getPrize() {
		return this.prize;
	}

	public void setPrize(Long prize) {
		this.prize = prize;
	}

	public Long getAdjust() {
		return this.adjust;
	}

	public void setAdjust(Long adjust) {
		this.adjust = adjust;
	}

	public Long getChange() {
		return this.change;
	}

	public void setChange(Long change) {
		this.change = change;
	}

	public String getMonth() {
		return month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getEdate() {
		return edate;
	}

	public void setEdate(String edate) {
		this.edate = edate;
	}

	public String getSdate() {
		return sdate;
	}

	public void setSdate(String sdate) {
		this.sdate = sdate;
	}

}