package com.crm.score.po;

import java.util.Date;

/**
 * TScorelog generated by MyEclipse Persistence Tools
 */

public class TScorelog implements java.io.Serializable {

	// Fields

	private Long id;

	private String phone;

	private Long beforescore;

	private Long afterscore;

	private String opertype;

	private String changeno;

	private String place;

	private String operater;

	private Date operdate;
	
	private Date start;
	
	private Date end;

	// Constructors

	public Date getEnd() {
		return end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public Date getStart() {
		return start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	/** default constructor */
	public TScorelog() {
	}

	/** full constructor */
	public TScorelog(String phone, Long beforescore, Long afterscore,
			String opertype, String changeno, String place, String operater,
			Date operdate) {
		this.phone = phone;
		this.beforescore = beforescore;
		this.afterscore = afterscore;
		this.opertype = opertype;
		this.changeno = changeno;
		this.place = place;
		this.operater = operater;
		this.operdate = operdate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Long getBeforescore() {
		return this.beforescore;
	}

	public void setBeforescore(Long beforescore) {
		this.beforescore = beforescore;
	}

	public Long getAfterscore() {
		return this.afterscore;
	}

	public void setAfterscore(Long afterscore) {
		this.afterscore = afterscore;
	}

	public String getOpertype() {
		return this.opertype;
	}

	public void setOpertype(String opertype) {
		this.opertype = opertype;
	}

	public String getChangeno() {
		return this.changeno;
	}

	public void setChangeno(String changeno) {
		this.changeno = changeno;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getOperater() {
		return this.operater;
	}

	public void setOperater(String operater) {
		this.operater = operater;
	}

	public Date getOperdate() {
		return this.operdate;
	}

	public void setOperdate(Date operdate) {
		this.operdate = operdate;
	}

}