package com.crm.score.po;

import java.util.Date;

/**
 * TTotalScore generated by MyEclipse Persistence Tools
 */

public class TTotalScore implements java.io.Serializable {

	// Fields

	private Long id;

	private String phone;

	private String vest;

	private Date invalidate;

	private Long vintegral;

	private Long invalible;

	private Long total;

	// Constructors

	/** default constructor */
	public TTotalScore() {
	}

	/** full constructor */
	public TTotalScore(String phone, String vest, Date invalidate,
			Long vintegral, Long invalible, Long total) {
		this.phone = phone;
		this.vest = vest;
		this.invalidate = invalidate;
		this.vintegral = vintegral;
		this.invalible = invalible;
		this.total = total;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getVest() {
		return this.vest;
	}

	public void setVest(String vest) {
		this.vest = vest;
	}

	public Date getInvalidate() {
		return this.invalidate;
	}

	public void setInvalidate(Date invalidate) {
		this.invalidate = invalidate;
	}

	public Long getVintegral() {
		return this.vintegral;
	}

	public void setVintegral(Long vintegral) {
		this.vintegral = vintegral;
	}

	public Long getInvalible() {
		return this.invalible;
	}

	public void setInvalible(Long invalible) {
		this.invalible = invalible;
	}

	public Long getTotal() {
		return this.total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}


}