/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.group.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-28-2009
 * 
 * XDoclet definition:
 * @struts.form name="groupViewForm"
 */
public class GroupViewForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** groupid property */
	private String groupid;

	/** grouplevel property */
	private String grouplevel;

	/** privince property */
	private String privince;

	/** vocation property */
	private String vocation;

	/** state property */
	private String state;

	/** manager property */
	private String manager;

	/** city property */
	private String city;

	/** groupname property */
	private String groupname;
	private String fcount;
	private String tcount;
	private String fmoney;
	private String tmoney;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the groupid.
	 * @return String
	 */
	public String getGroupid() {
		return groupid;
	}

	/** 
	 * Set the groupid.
	 * @param groupid The groupid to set
	 */
	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	/** 
	 * Returns the grouplevel.
	 * @return String
	 */
	public String getGrouplevel() {
		return grouplevel;
	}

	/** 
	 * Set the grouplevel.
	 * @param grouplevel The grouplevel to set
	 */
	public void setGrouplevel(String grouplevel) {
		this.grouplevel = grouplevel;
	}

	/** 
	 * Returns the privince.
	 * @return String
	 */
	public String getPrivince() {
		return privince;
	}

	/** 
	 * Set the privince.
	 * @param privince The privince to set
	 */
	public void setPrivince(String privince) {
		this.privince = privince;
	}

	/** 
	 * Returns the vocation.
	 * @return String
	 */
	public String getVocation() {
		return vocation;
	}

	/** 
	 * Set the vocation.
	 * @param vocation The vocation to set
	 */
	public void setVocation(String vocation) {
		this.vocation = vocation;
	}

	/** 
	 * Returns the state.
	 * @return String
	 */
	public String getState() {
		return state;
	}

	/** 
	 * Set the state.
	 * @param state The state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

	/** 
	 * Returns the manager.
	 * @return String
	 */
	public String getManager() {
		return manager;
	}

	/** 
	 * Set the manager.
	 * @param manager The manager to set
	 */
	public void setManager(String manager) {
		this.manager = manager;
	}

	/** 
	 * Returns the city.
	 * @return String
	 */
	public String getCity() {
		return city;
	}

	/** 
	 * Set the city.
	 * @param city The city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/** 
	 * Returns the groupname.
	 * @return String
	 */
	public String getGroupname() {
		return groupname;
	}

	/** 
	 * Set the groupname.
	 * @param groupname The groupname to set
	 */
	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	public String getFcount() {
		return fcount;
	}

	public void setFcount(String fcount) {
		this.fcount = fcount;
	}

	public String getFmoney() {
		return fmoney;
	}

	public void setFmoney(String fmoney) {
		this.fmoney = fmoney;
	}

	public String getTcount() {
		return tcount;
	}

	public void setTcount(String tcount) {
		this.tcount = tcount;
	}

	public String getTmoney() {
		return tmoney;
	}

	public void setTmoney(String tmoney) {
		this.tmoney = tmoney;
	}


}