/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.group.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-26-2009
 * 
 * XDoclet definition:
 * @struts.form name="groupForm"
 */
public class GroupForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	private String groupid;//集团ID

	private String groupname;//集团名称

	private String vocation;//所属行业

	private String grouplevel;//企业级别
    private String province;//省
	private String city;//市
	private String area;//地区
    private String secity;//修改页面的市
	private String manager;//客户经理

	private String state;//集团状态
	private String name;//姓名

	private String telephone;//联系电话

	private String job;//职位

	private String sex;//性别

	private String email;//EMAIL
	private  String address ;//地址
    private String post; //邮编
    private String[] sel;//选择集团的选框
    private String useman ;//法人
    private String web ;//网址
    private String openmon ;//注册资金
    private String moneytype ;//财务状况
    private String sendtype ;//营运状况
    private String empcount ;//员工数量
    private String grouptype ;//企业性质
    private FormFile files;
	private String army;//是否党政军
	

	public String getArmy() {
		return army;
	}

	public void setArmy(String army) {
		this.army = army;
	}



	public FormFile getFiles() {
		return files;
	}

	public String[] getSel() {
		return sel;
	}

	public void setSel(String[] sel) {
		this.sel = sel;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPost() {
		return post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.sex="0";
		this.army="0";
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getGroupid() {
		return groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getGrouplevel() {
		return grouplevel;
	}

	public void setGrouplevel(String grouplevel) {
		this.grouplevel = grouplevel;
	}

	public String getGroupname() {
		return groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	

	

	public String getManager() {
		return manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getVocation() {
		return vocation;
	}

	public void setVocation(String vocation) {
		this.vocation = vocation;
	}

	public String getSecity() {
		return secity;
	}

	public void setSecity(String secity) {
		this.secity = secity;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public void setFiles(FormFile files) {
		this.files = files;
	}

	public String getEmpcount() {
		return empcount;
	}

	public void setEmpcount(String empcount) {
		this.empcount = empcount;
	}

	public String getGrouptype() {
		return grouptype;
	}

	public void setGrouptype(String grouptype) {
		this.grouptype = grouptype;
	}

	public String getMoneytype() {
		return moneytype;
	}

	public void setMoneytype(String moneytype) {
		this.moneytype = moneytype;
	}

	public String getOpenmon() {
		return openmon;
	}

	public void setOpenmon(String openmon) {
		this.openmon = openmon;
	}

	public String getSendtype() {
		return sendtype;
	}

	public void setSendtype(String sendtype) {
		this.sendtype = sendtype;
	}

	public String getUseman() {
		return useman;
	}

	public void setUseman(String useman) {
		this.useman = useman;
	}

	public String getWeb() {
		return web;
	}

	public void setWeb(String web) {
		this.web = web;
	}
}