package com.crm.pub.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable {

	// Fields

	private String userid;//用户ID

	private String username;//用户名

	private String password;//密码

	private String sex;//性别

	private String homeplace;//籍贯

	private String code;//身份证号码

	private String tel;//电话号码

	private String email;//E——MAIL

	private String phone;//手机

	private String address;//地址

	private String jobno;//工号

	private Date opendate;//开户日期

	private String slock;//是否冻结

	//设置角色
	private Set<TRole>  roles = new HashSet<TRole>();
	
	//设置角色
	private Set<TPower>  powers = new HashSet<TPower>();

	// Constructors

	/** default constructor */
	public TUser() {
	}

	/** full constructor */
	public TUser(String username, String password, String sex,
			String homeplace, String code, String tel, String email,
			String phone, String address, String jobno, Date opendate,
			String slock) {
		this.username = username;
		this.password = password;
		this.sex = sex;
		this.homeplace = homeplace;
		this.code = code;
		this.tel = tel;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.jobno = jobno;
		this.opendate = opendate;
		this.slock = slock;
	}

	// Property accessors

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getHomeplace() {
		return this.homeplace;
	}

	public void setHomeplace(String homeplace) {
		this.homeplace = homeplace;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getJobno() {
		return this.jobno;
	}

	public void setJobno(String jobno) {
		this.jobno = jobno;
	}

	public Date getOpendate() {
		return this.opendate;
	}

	public void setOpendate(Date opendate) {
		this.opendate = opendate;
	}

	public String getSlock() {
		return this.slock;
	}

	public void setSlock(String slock) {
		this.slock = slock;
	}

	public Set<TRole> getRoles() {
		return roles;
	}

	public void setRoles(Set<TRole> roles) {
		this.roles = roles;
	}

	public Set<TPower> getPowers() {
		return powers;
	}

	public void setPowers(Set<TPower> powers) {
		this.powers = powers;
	}

}