package com.crm.group.po;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClubActivity generated by MyEclipse Persistence Tools
 */

public class ClubActivity implements java.io.Serializable {

	// Fields

	private Long actId;//活动ID

	private Date actTime;//时间

	private String actAddr;//地点

	private String actContent;//内容

	private String organizer;//组织者

	private Long intendCount;//预计参加人数

	private Long factCount;//实际参加人数

	private Long budgFees;//预计费用

	private Long factFees;//实际费用

	private String ischeck;//审核情况
	private Set<TFees> fee=new HashSet<TFees> ();//费用详细表

	// Constructors

	/** default constructor */
	public ClubActivity() {
	}

	/** full constructor */
	public ClubActivity(Date actTime, String actAddr, String actContent,
			String organizer, Long intendCount, Long factCount, Long budgFees,
			Long factFees, String ischeck) {
		this.actTime = actTime;
		this.actAddr = actAddr;
		this.actContent = actContent;
		this.organizer = organizer;
		this.intendCount = intendCount;
		this.factCount = factCount;
		this.budgFees = budgFees;
		this.factFees = factFees;
		this.ischeck = ischeck;
	}

	// Property accessors

	public Long getActId() {
		return this.actId;
	}

	public void setActId(Long actId) {
		this.actId = actId;
	}

	public Date getActTime() {
		return this.actTime;
	}

	public void setActTime(Date actTime) {
		this.actTime = actTime;
	}

	public String getActAddr() {
		return this.actAddr;
	}

	public void setActAddr(String actAddr) {
		this.actAddr = actAddr;
	}

	public String getActContent() {
		return this.actContent;
	}

	public void setActContent(String actContent) {
		this.actContent = actContent;
	}

	public String getOrganizer() {
		return this.organizer;
	}

	public void setOrganizer(String organizer) {
		this.organizer = organizer;
	}

	public Long getIntendCount() {
		return this.intendCount;
	}

	public void setIntendCount(Long intendCount) {
		this.intendCount = intendCount;
	}

	public Long getFactCount() {
		return this.factCount;
	}

	public void setFactCount(Long factCount) {
		this.factCount = factCount;
	}

	public Long getBudgFees() {
		return this.budgFees;
	}

	public void setBudgFees(Long budgFees) {
		this.budgFees = budgFees;
	}

	public Long getFactFees() {
		return this.factFees;
	}

	public void setFactFees(Long factFees) {
		this.factFees = factFees;
	}

	
	public Set<TFees> getFee() {
		return fee;
	}

	public void setFee(Set<TFees> fee) {
		this.fee = fee;
	}

	public void setIscheck(String ischeck) {
		this.ischeck = ischeck;
	}

	public String getIscheck() {
		return ischeck;
	}

}