package com.crm.group.po;

import java.util.Date;

/**
 * TFee generated by MyEclipse Persistence Tools
 */

public class TFee implements java.io.Serializable {

	// Fields

	private Long id;

	private String phone;

	private Long inputfee;

	private Long fullfee;

	private Long arrearage;

	private Date feedate;

	private Long hire;

	private Long basicfee;

	private Long roamfee;

	private Long infofee;

	private Long upfee;

	private Long otherfee;

	private Long roamdate;

	private Long noroamdate;

	private Long longdate;

	private Long nolongdate;

	private Long roamtime;

	private Long noroamtime;

	private Long longtime;

	private Long nolongtime;

	private Long longfee;

	// Constructors

	/** default constructor */
	public TFee() {
	}

	/** full constructor */
	public TFee(String phone, Long inputfee, Long fullfee, Long arrearage,
			Date feedate, Long hire, Long basicfee, Long roamfee, Long infofee,
			Long upfee, Long otherfee, Long roamdate, Long noroamdate,
			Long longdate, Long nolongdate, Long roamtime, Long noroamtime,
			Long longtime, Long nolongtime, Long longfee) {
		this.phone = phone;
		this.inputfee = inputfee;
		this.fullfee = fullfee;
		this.arrearage = arrearage;
		this.feedate = feedate;
		this.hire = hire;
		this.basicfee = basicfee;
		this.roamfee = roamfee;
		this.infofee = infofee;
		this.upfee = upfee;
		this.otherfee = otherfee;
		this.roamdate = roamdate;
		this.noroamdate = noroamdate;
		this.longdate = longdate;
		this.nolongdate = nolongdate;
		this.roamtime = roamtime;
		this.noroamtime = noroamtime;
		this.longtime = longtime;
		this.nolongtime = nolongtime;
		this.longfee = longfee;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Long getInputfee() {
		return this.inputfee;
	}

	public void setInputfee(Long inputfee) {
		this.inputfee = inputfee;
	}

	public Long getFullfee() {
		return this.fullfee;
	}

	public void setFullfee(Long fullfee) {
		this.fullfee = fullfee;
	}

	public Long getArrearage() {
		return this.arrearage;
	}

	public void setArrearage(Long arrearage) {
		this.arrearage = arrearage;
	}

	public Date getFeedate() {
		return this.feedate;
	}

	public void setFeedate(Date feedate) {
		this.feedate = feedate;
	}

	public Long getHire() {
		return this.hire;
	}

	public void setHire(Long hire) {
		this.hire = hire;
	}

	public Long getBasicfee() {
		return this.basicfee;
	}

	public void setBasicfee(Long basicfee) {
		this.basicfee = basicfee;
	}

	public Long getRoamfee() {
		return this.roamfee;
	}

	public void setRoamfee(Long roamfee) {
		this.roamfee = roamfee;
	}

	public Long getInfofee() {
		return this.infofee;
	}

	public void setInfofee(Long infofee) {
		this.infofee = infofee;
	}

	public Long getUpfee() {
		return this.upfee;
	}

	public void setUpfee(Long upfee) {
		this.upfee = upfee;
	}

	public Long getOtherfee() {
		return this.otherfee;
	}

	public void setOtherfee(Long otherfee) {
		this.otherfee = otherfee;
	}

	public Long getRoamdate() {
		return this.roamdate;
	}

	public void setRoamdate(Long roamdate) {
		this.roamdate = roamdate;
	}

	public Long getNoroamdate() {
		return this.noroamdate;
	}

	public void setNoroamdate(Long noroamdate) {
		this.noroamdate = noroamdate;
	}

	public Long getLongdate() {
		return this.longdate;
	}

	public void setLongdate(Long longdate) {
		this.longdate = longdate;
	}

	public Long getNolongdate() {
		return this.nolongdate;
	}

	public void setNolongdate(Long nolongdate) {
		this.nolongdate = nolongdate;
	}

	public Long getRoamtime() {
		return this.roamtime;
	}

	public void setRoamtime(Long roamtime) {
		this.roamtime = roamtime;
	}

	public Long getNoroamtime() {
		return this.noroamtime;
	}

	public void setNoroamtime(Long noroamtime) {
		this.noroamtime = noroamtime;
	}

	public Long getLongtime() {
		return this.longtime;
	}

	public void setLongtime(Long longtime) {
		this.longtime = longtime;
	}

	public Long getNolongtime() {
		return this.nolongtime;
	}

	public void setNolongtime(Long nolongtime) {
		this.nolongtime = nolongtime;
	}

	public Long getLongfee() {
		return this.longfee;
	}

	public void setLongfee(Long longfee) {
		this.longfee = longfee;
	}

}