package com.crm.group.po;

/**
 * TGrouplinker generated by MyEclipse Persistence Tools
 */

public class TGrouplinker implements java.io.Serializable {

	// Fields

	private String groupid;//集团ID

	private String name;//姓名

	private String telephone;//联系电话

	private String job;//职位

	private String sex;//性别

	private String email;//EMAIL



	/** default constructor */
	public TGrouplinker() {
	}

	/** full constructor */
	public TGrouplinker(String name, String telephone, String job, String sex,
			String email) {
		this.name = name;
		this.telephone = telephone;
		this.job = job;
		this.sex = sex;
		this.email = email;
	}

	// Property accessors

	

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGroupid() {
		return groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

}