package com.crm.group.po;

import java.util.Date;

/**
 * TGrouplog generated by MyEclipse Persistence Tools
 */

public class TGrouplog implements java.io.Serializable {

	// Fields

	private Long logid;//日志ID

	private String groupid;//集团ID

	private Date opentime;//操作时间
    private String operationer;//操作人
	private String opens;//操作类型
	

	// Constructors

	

	/** default constructor */
	public TGrouplog() {
	}

	/** full constructor */
	public TGrouplog(String groupid, Date opentime, String opens,String operationer) {
		this.groupid = groupid;
		this.opentime = opentime;
		this.opens = opens;
		this.operationer=operationer;
	}

	// Property accessors

	public Long getLogid() {
		return this.logid;
	}

	public void setLogid(Long logid) {
		this.logid = logid;
	}

	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public Date getOpentime() {
		return this.opentime;
	}

	public void setOpentime(Date opentime) {
		this.opentime = opentime;
	}

	public String getOpens() {
		return this.opens;
	}

	public void setOpens(String opens) {
		this.opens = opens;
	}

	public String getOperationer() {
		return operationer;
	}

	public void setOperationer(String operationer) {
		this.operationer = operationer;
	}

}