/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.pub.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 10-22-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="roleForm"
 */
public class RoleForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** rolename property */
	private String rolename;

	/** roleid property */
	private String roleid;
	/** rolepower property */
	private String menus[];

	/** descript property */
	private String descript;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the rolename.
	 * 
	 * @return String
	 */
	public String getRolename() {
		return rolename;
	}

	/**
	 * Set the rolename.
	 * 
	 * @param rolename
	 *            The rolename to set
	 */
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	/**
	 * Returns the roleid.
	 * 
	 * @return String
	 */
	public String getRoleid() {
		return roleid;
	}

	/**
	 * Set the roleid.
	 * 
	 * @param roleid
	 *            The roleid to set
	 */
	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	/**
	 * Returns the descript.
	 * 
	 * @return String
	 */
	public String getDescript() {
		return descript;
	}

	/**
	 * Set the descript.
	 * 
	 * @param descript
	 *            The descript to set
	 */
	public void setDescript(String descript) {
		this.descript = descript;
	}

	public String[] getMenus() {
		return menus;
	}

	public void setMenus(String[] menus) {
		this.menus = menus;
	}




}