package com.crm.sysdo.po;

/**
 * TData generated by MyEclipse Persistence Tools
 */

public class TData implements java.io.Serializable {

	// Fields

	private Long id;

	private String name;

	private Long pid;

	private String remark;

	// Constructors

	/** default constructor */
	public TData() {
	}

	/** full constructor */
	public TData(String name, Long pid, String remark) {
		this.name = name;
		this.pid = pid;
		this.remark = remark;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}