/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.sysdo.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.crm.page.PageUtil;
import com.crm.per.dao.Permission;
import com.crm.pub.GlobVar;
import com.crm.sysdo.po.TCollect;
import com.crm.sysdo.po.TData;
import com.crm.sysdo.service.inf.CollectServiceDao;
import com.crm.sysdo.service.inf.DataServiceDao;
import com.crm.sysdo.struts.form.CollectForm;
import com.crm.sysdo.struts.form.DataForm;

/**
 * MyEclipse Struts Creation date: 10-23-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/admin/data" name="dataForm" input="/form/data.jsp"
 *                parameter="task" scope="request" validate="true"
 */
public class CollectAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private CollectServiceDao collectServiceDao;
	private Permission perDao;

	/**
	 * 跳转到添加数字字典界面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toAddData(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		// 32 角色
		List sonList = perDao.getSonPerList("33");
		request.setAttribute("sonPowerByMenu", sonList);

		return new ActionForward("/admin/sysdo/data/adddata.jsp");
	}

	/**
	 * 添加
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addData(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		CollectForm collectForm = (CollectForm) form;
		TCollect Collect = new TCollect();
		BeanUtils.copyProperties(Collect, collectForm);

		List list = this.collectServiceDao.searchCollect(Collect);
		if (list.size() > 0) {
			response.getWriter().print(
					"<script> alert('数字字典的名称已经存在！请重新输入！！');location.href='"
							+ request.getContextPath()
							+ "/admin/Collect.do?task=toAddCollect';</script>");
			return null;
		}

		Boolean bool = this.collectServiceDao.addCollect(Collect);

		if (bool) {
			response
					.getWriter()
					.print(
							"<script> if(confirm('添加成功！是否继续添加？')){location.href='"
									+ request.getContextPath()
									+ "/admin/Collect.do?task=toAddCollect';}else{location.href='"
									+ request.getContextPath()
									+ "/admin/Collect.do?task=CollectList';}</script>");
			return null;
		} else {
			response
					.getWriter()
					.print(
							"<script> if(confirm('添加失败！是否重试？')){location.href='"
									+ request.getContextPath()
									+ "/admin/Collect.do?task=toAddCollect';}else{location.href='"
									+ request.getContextPath()
									+ "/admin/Collect.do?task=CollectList';}</script>");
			return null;
		}
	}

	/**
	 * 数字字典列表
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward CollectList(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		CollectForm CollectForm = (CollectForm) form;
		PageUtil pageUtil = new PageUtil(request, this.collectServiceDao
				.getCount(), GlobVar.PAGESIZE_BY_TWENTY_DATA);
		request.setAttribute("pageUtil", pageUtil);

		List sonList = this.collectServiceDao.searchCollect(null);
		request.setAttribute("CollectSonList", sonList);

		// 32 角色
		List sl = perDao.getSonPerList("33");
		request.setAttribute("sonPowerByMenu", sl);
		return new ActionForward("/admin/sysdo/Collect/Collectlist.jsp");
	}

	/**
	 * 删除数字字典
	 * 
	 * 连同子类一起删除
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward deleteCollect(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		CollectForm CollectForm = (CollectForm) form;

		TCollect Collect = new TCollect();
		Collect.setId(new Long(CollectForm.getId()));

		Boolean bool = this.collectServiceDao.deleteCollect(Collect);

		if (bool) {
			response.getWriter().print(
					"<script> alert('删除成功!将返回数字字典列表!');location.href='"
							+ request.getContextPath()
							+ "/admin/Collect.do?task=CollectList';</script>");
		} else {
			response.getWriter().print(
					"<script> alert('删除失败,请重试!');location.href='"
							+ request.getContextPath()
							+ "/admin/Collect.do?task=CollectList';</script>");
		}
		return null;
	}

	/**
	 * 跳转到修改页面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toUpdateCollect(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		CollectForm CollectForm = (CollectForm) form;
		TCollect Collect = this.collectServiceDao.seachCollect(new Long(CollectForm.getId()));
		BeanUtils.copyProperties(CollectForm, Collect);

		

		// 32 角色
		List sonList = perDao.getSonPerList("33");
		request.setAttribute("sonPowerByMenu", sonList);

		return new ActionForward("/admin/sysdo/Collect/updateCollect.jsp");
	}

	/**
	 * 修改
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward updateCollect(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		CollectForm CollectForm = (CollectForm) form;
		TCollect Collect = this.collectServiceDao.seachCollect(new Long(CollectForm.getId()));
		BeanUtils.copyProperties(Collect, CollectForm);

		Boolean bool = false;
		try {
			bool = this.collectServiceDao.updateCollect(Collect);
		} catch (Exception e) {
			e.printStackTrace();
		}
		if (bool) {
			response
					.getWriter()
					.print(
							"<script>if(confirm('数字字典修改成功,是否继续修改!')){location.href='"
									+ request.getContextPath()
									+ "/admin/Collect.do?task=toUpdateCollect&id="
									+ Collect.getId()
									+ "';}else{location.href='"
									+ request.getContextPath()
									+ "/admin/Collect.do?task=CollectList';}</script>");

		} else {
			response.getWriter().print("<script>alert('数字字典修改失败,请重试!');location.href='"
							+ request.getContextPath()
							+ "/admin/Collect.do?task=toUpdateCollect&id='"
							+ Collect.getId() + "';</script>");
		}
		return null;
	}

	public CollectServiceDao getCollectServiceDao() {
		return collectServiceDao;
	}

	public void setCollectServiceDao(CollectServiceDao CollectServiceDao) {
		this.collectServiceDao = CollectServiceDao;
	}

	public Permission getPerDao() {
		return perDao;
	}

	public void setPerDao(Permission perDao) {
		this.perDao = perDao;
	}
}