/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.sysdo.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.crm.page.PageUtil;
import com.crm.per.dao.Permission;
import com.crm.pub.GlobVar;
import com.crm.sysdo.po.TManufacturer;
import com.crm.sysdo.service.inf.ManufacturerServiceDao;
import com.crm.sysdo.struts.form.ManuFacturerForm;

/**
 * MyEclipse Struts Creation date: 10-23-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/admin/data" name="dataForm" input="/form/data.jsp"
 *                parameter="task" scope="request" validate="true"
 */
public class ManufacturerAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private ManufacturerServiceDao ManuServiceDao;
	private Permission perDao;

	/**
	 * 跳转到添加数字字典界面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toAddManu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		// 32 角色
		List sonList = perDao.getSonPerList("33");
		request.setAttribute("sonPowerByMenu", sonList);

		return new ActionForward("/admin/sysdo/Manu/addManu.jsp");
	}

	/**
	 * 添加
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addManu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		ManuFacturerForm ManuForm = (ManuFacturerForm) form;
		TManufacturer Manu = new TManufacturer();
		BeanUtils.copyProperties(Manu, ManuForm);


		Boolean bool = this.ManuServiceDao.addManufacturer(Manu);

		if (bool) {
			response
					.getWriter()
					.print(
							"<script> if(confirm('添加成功！是否继续添加？')){location.href='"
									+ request.getContextPath()
									+ "/admin/Manu.do?task=toAddManu';}else{location.href='"
									+ request.getContextPath()
									+ "/admin/Manu.do?task=ManuList';}</script>");
			return null;
		} else {
			response
					.getWriter()
					.print(
							"<script> if(confirm('添加失败！是否重试？')){location.href='"
									+ request.getContextPath()
									+ "/admin/Manu.do?task=toAddManu';}else{location.href='"
									+ request.getContextPath()
									+ "/admin/Manu.do?task=ManuList';}</script>");
			return null;
		}
	}

	/**
	 * 数字字典列表
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward ManuList(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		ManuFacturerForm ManuForm = (ManuFacturerForm) form;
		PageUtil pageUtil = new PageUtil(request, this.ManuServiceDao
				.getCount(null), GlobVar.PAGESIZE_BY_TWENTY_DATA);
		request.setAttribute("pageUtil", pageUtil);


		// 32 角色
		List sl = perDao.getSonPerList("33");
		request.setAttribute("sonPowerByMenu", sl);
		return new ActionForward("/admin/sysdo/Manu/Manulist.jsp");
	}

	/**
	 * 删除数字字典
	 * 
	 * 连同子类一起删除
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward deleteManu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		ManuFacturerForm ManuForm = (ManuFacturerForm) form;

		TManufacturer Manu = new TManufacturer();
		Manu.setId(new Long(ManuForm.getId()));

		Boolean bool = this.ManuServiceDao.deleteManufacturer(Manu);

		if (bool) {
			response.getWriter().print(
					"<script> alert('删除成功!将返回数字字典列表!');location.href='"
							+ request.getContextPath()
							+ "/admin/Manu.do?task=ManuList';</script>");
		} else {
			response.getWriter().print(
					"<script> alert('删除失败,请重试!');location.href='"
							+ request.getContextPath()
							+ "/admin/Manu.do?task=ManuList';</script>");
		}
		return null;
	}

	/**
	 * 跳转到修改页面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward toUpdateManu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		ManuFacturerForm ManuForm = (ManuFacturerForm) form;
		TManufacturer Manu = this.ManuServiceDao.getManufacturerById(new Long(ManuForm.getId()));
		BeanUtils.copyProperties(ManuForm, Manu);

		// 32 角色
		List sonList = perDao.getSonPerList("33");
		request.setAttribute("sonPowerByMenu", sonList);

		return new ActionForward("/admin/sysdo/Manu/updateManu.jsp");
	}

	/**
	 * 修改
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward updateManu(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		ManuFacturerForm ManuForm = (ManuFacturerForm) form;
		TManufacturer Manu = this.ManuServiceDao.getManufacturerById(new Long(ManuForm.getId()));
		BeanUtils.copyProperties(Manu, ManuForm);

		Boolean bool = false;
		try {
			bool = this.ManuServiceDao.updateManufacturer(Manu);
		} catch (Exception e) {
			e.printStackTrace();
		}
		if (bool) {
			response
					.getWriter()
					.print(
							"<script>if(confirm('数字字典修改成功,是否继续修改!')){location.href='"
									+ request.getContextPath()
									+ "/admin/Manu.do?task=toUpdateManu&id="
									+ Manu.getId()
									+ "';}else{location.href='"
									+ request.getContextPath()
									+ "/admin/Manu.do?task=ManuList';}</script>");

		} else {
			response.getWriter().print("<script>alert('数字字典修改失败,请重试!');location.href='"
							+ request.getContextPath()
							+ "/admin/Manu.do?task=toUpdateManu&id='"
							+ Manu.getId() + "';</script>");
		}
		return null;
	}

	public ManufacturerServiceDao getManuServiceDao() {
		return ManuServiceDao;
	}

	public void setManuServiceDao(ManufacturerServiceDao ManuServiceDao) {
		this.ManuServiceDao = ManuServiceDao;
	}

	public Permission getPerDao() {
		return perDao;
	}

	public void setPerDao(Permission perDao) {
		this.perDao = perDao;
	}
}