/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.client.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/**
 * MyEclipse Struts Creation date: 10-27-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="clientForm"
 */
public class ClientForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	private String phone; // 手机号

	private String name; // 姓名

	private String type;// 证件类型

	private String code;// 证件号

	private Long provice;// 省份

	private Long city;// 城市

	private String room;// 营业厅

	private String address; // 地址

	private Long grade; // 等级

	private Long area; // 地区

	private Long brand;// 品牌

	private String reg_date; // 注册时间

	private String linkman; // 维系人

	private String isparty;// 是否为党政军

	private String isgroup; // 是否为集团用户

	private String ischeck; // 信息是否验证

	private String bigdate; // 成为大客户时间

	/**
	 * 个性资料
	 */

	private String sex; // 性别

	private String birth; // 生日 --birthday

	private Long age; // 年龄

	private String love[]; // 爱好 ----loves

	private String familyphone; // 电话

	private String officephone;// 办公电话

	private String fax; // 传真

	private String email; // email

	private String officeaddress;// 办公地址

	private String trade; // 行业

	private String iscar; // 是否有车

	private String marriagedate; // 结婚日 --marrdate

	private String nation; // 籍贯

	private String country; // 国籍

	private String num;// 邮编

	private String phones[]; // 要导出的客户手机号

	private String startfee; // 开始花费

	private String endfee; // 结束花费

	/**
	 * 手动分级日志
	 */
	private String checkuser;

	private String checktime;

	private String checkno;

	private Long oldgrade;

	private Long newgrade;

	
	private Long sascore;//起始积分

	private Long endscore;//结束积分

	private Long safee;//起始话费

	private Long efee;//结束话费
	
	private String start; //起始时间
	
	private String end;//结束时间
	
	private FormFile exlFile;//导入文件路径
	
	private String manager;//客户经理

	public FormFile getExlFile() {
		return exlFile;
	}

	public void setExlFile(FormFile exlFile) {
		this.exlFile = exlFile;
	}

	public Long getEfee() {
		return efee;
	}

	public void setEfee(Long efee) {
		this.efee = efee;
	}

	public Long getEndscore() {
		return endscore;
	}

	public void setEndscore(Long endscore) {
		this.endscore = endscore;
	}

	public Long getSafee() {
		return safee;
	}

	public void setSafee(Long safee) {
		this.safee = safee;
	}

	public Long getSascore() {
		return sascore;
	}

	public void setSascore(Long sascore) {
		this.sascore = sascore;
	}

	public Long getAge() {
		return age;
	}

	public void setAge(Long age) {
		this.age = age;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFamilyphone() {
		return familyphone;
	}

	public void setFamilyphone(String familyphone) {
		this.familyphone = familyphone;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getIscar() {
		return iscar;
	}

	public void setIscar(String iscar) {
		this.iscar = iscar;
	}

	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getOfficeaddress() {
		return officeaddress;
	}

	public void setOfficeaddress(String officeaddress) {
		this.officeaddress = officeaddress;
	}

	public String getOfficephone() {
		return officephone;
	}

	public void setOfficephone(String officephone) {
		this.officephone = officephone;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getTrade() {
		return trade;
	}

	public void setTrade(String trade) {
		this.trade = trade;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Long getArea() {
		return area;
	}

	public void setArea(Long area) {
		this.area = area;
	}

	public Long getBrand() {
		return brand;
	}

	public void setBrand(Long brand) {
		this.brand = brand;
	}

	public Long getCity() {
		return city;
	}

	public void setCity(Long city) {
		this.city = city;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Long getGrade() {
		return grade;
	}

	public void setGrade(Long grade) {
		this.grade = grade;
	}

	public String getIscheck() {
		return ischeck;
	}

	public void setIscheck(String ischeck) {
		this.ischeck = ischeck;
	}

	public String getIsgroup() {
		return isgroup;
	}

	public void setIsgroup(String isgroup) {
		this.isgroup = isgroup;
	}

	public String getIsparty() {
		return isparty;
	}

	public void setIsparty(String isparty) {
		this.isparty = isparty;
	}

	public String getLinkman() {
		return linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Long getProvice() {
		return provice;
	}

	public void setProvice(Long provice) {
		this.provice = provice;
	}

	public String getRoom() {
		return room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String[] getLove() {
		return love;
	}

	public void setLove(String[] love) {
		this.love = love;
	}

	public String getBigdate() {
		return bigdate;
	}

	public void setBigdate(String bigdate) {
		this.bigdate = bigdate;
	}

	public String getBirth() {
		return birth;
	}

	public void setBirth(String birth) {
		this.birth = birth;
	}

	public String getMarriagedate() {
		return marriagedate;
	}

	public void setMarriagedate(String marriagedate) {
		this.marriagedate = marriagedate;
	}

	public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getReg_date() {
		return reg_date;
	}

	public void setReg_date(String reg_date) {
		this.reg_date = reg_date;
	}

	public String[] getPhones() {
		return phones;
	}

	public void setPhones(String[] phones) {
		this.phones = phones;
	}

	public String getEndfee() {
		return endfee;
	}

	public void setEndfee(String endfee) {
		this.endfee = endfee;
	}

	public String getStartfee() {
		return startfee;
	}

	public void setStartfee(String startfee) {
		this.startfee = startfee;
	}

	public String getCheckno() {
		return checkno;
	}

	public void setCheckno(String checkno) {
		this.checkno = checkno;
	}

	public String getCheckuser() {
		return checkuser;
	}

	public void setCheckuser(String checkuser) {
		this.checkuser = checkuser;
	}

	public Long getNewgrade() {
		return newgrade;
	}

	public void setNewgrade(Long newgrade) {
		this.newgrade = newgrade;
	}

	public Long getOldgrade() {
		return oldgrade;
	}

	public void setOldgrade(Long oldgrade) {
		this.oldgrade = oldgrade;
	}

	public String getChecktime() {
		return checktime;
	}

	public void setChecktime(String checktime) {
		this.checktime = checktime;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	public String getStart() {
		return start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getManager() {
		return manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

}