package com.crm.client.po;

import java.util.Date;

/**
 * TClientallot generated by MyEclipse Persistence Tools
 */

public class TClientallot implements java.io.Serializable {

	// Fields

	private Long id;

	private String phone;

	private String userid;

	private String manager;

	private String state;
	
	private Date fdate;
	
	private Date cdate;
	
	private Date sadate;
	
	private Date edate;
	
	// Constructors

	public Date getEdate() {
		return edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

	public Date getSadate() {
		return sadate;
	}

	public void setSadate(Date sadate) {
		this.sadate = sadate;
	}

	/** default constructor */
	public TClientallot() {
	}

	/** full constructor */
	public TClientallot(String phone, String manager, String state) {
		this.phone = phone;
		this.manager = manager;
		this.state = state;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getCdate() {
		return cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public Date getFdate() {
		return fdate;
	}

	public void setFdate(Date fdate) {
		this.fdate = fdate;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

}