package com.crm.client.po;

import java.util.Date;

/**
 * TOperation generated by MyEclipse Persistence Tools
 */

public class TOperation implements java.io.Serializable {

	// Fields

	private Long id;

	private String type1;

	private String type2;

	private String type3;

	private String type4;

	private String type5;

	private String phone;

	private Date regdate;

	private String reguser;

	private String state;

	private String checkuser;

	private Date checkdate;

	private String openstate;

	private String canuserdate;

	private String call;

	private String move;

	private String creditfee;

	private String factfee;

	private String why;

	private String address;

	private String ischeck;

	private String remarks;

	private String name;

	private Date codetime;

	private String codetype;
	
	private String result;

	// Constructors

	/** default constructor */
	public TOperation() {
	}

	/** full constructor */
	public TOperation(String type1, String type2, String type3, String type4,
			String type5, String phone, Date regdate, String reguser,
			String state, String checkuser, Date checkdate, String openstate,
			String canuserdate, String call, String move, String creditfee,
			String factfee, String why, String address, String ischeck,
			String remarks, String name, Date codetime, String codetype,String result) {
		this.type1 = type1;
		this.type2 = type2;
		this.type3 = type3;
		this.type4 = type4;
		this.type5 = type5;
		this.phone = phone;
		this.regdate = regdate;
		this.reguser = reguser;
		this.state = state;
		this.checkuser = checkuser;
		this.checkdate = checkdate;
		this.openstate = openstate;
		this.canuserdate = canuserdate;
		this.call = call;
		this.move = move;
		this.creditfee = creditfee;
		this.factfee = factfee;
		this.why = why;
		this.address = address;
		this.ischeck = ischeck;
		this.remarks = remarks;
		this.name = name;
		this.codetime = codetime;
		this.codetype = codetype;
		this.result = result;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getType1() {
		return this.type1;
	}

	public void setType1(String type1) {
		this.type1 = type1;
	}

	public String getType2() {
		return this.type2;
	}

	public void setType2(String type2) {
		this.type2 = type2;
	}

	public String getType3() {
		return this.type3;
	}

	public void setType3(String type3) {
		this.type3 = type3;
	}

	public String getType4() {
		return this.type4;
	}

	public void setType4(String type4) {
		this.type4 = type4;
	}

	public String getType5() {
		return this.type5;
	}

	public void setType5(String type5) {
		this.type5 = type5;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getRegdate() {
		return this.regdate;
	}

	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	public String getReguser() {
		return this.reguser;
	}

	public void setReguser(String reguser) {
		this.reguser = reguser;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCheckuser() {
		return this.checkuser;
	}

	public void setCheckuser(String checkuser) {
		this.checkuser = checkuser;
	}

	public Date getCheckdate() {
		return this.checkdate;
	}

	public void setCheckdate(Date checkdate) {
		this.checkdate = checkdate;
	}

	public String getOpenstate() {
		return this.openstate;
	}

	public void setOpenstate(String openstate) {
		this.openstate = openstate;
	}

	public String getCanuserdate() {
		return this.canuserdate;
	}

	public void setCanuserdate(String canuserdate) {
		this.canuserdate = canuserdate;
	}

	public String getCall() {
		return this.call;
	}

	public void setCall(String call) {
		this.call = call;
	}

	public String getMove() {
		return this.move;
	}

	public void setMove(String move) {
		this.move = move;
	}

	public String getCreditfee() {
		return this.creditfee;
	}

	public void setCreditfee(String creditfee) {
		this.creditfee = creditfee;
	}

	public String getFactfee() {
		return this.factfee;
	}

	public void setFactfee(String factfee) {
		this.factfee = factfee;
	}

	public String getWhy() {
		return this.why;
	}

	public void setWhy(String why) {
		this.why = why;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getIscheck() {
		return this.ischeck;
	}

	public void setIscheck(String ischeck) {
		this.ischeck = ischeck;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCodetime() {
		return this.codetime;
	}

	public void setCodetime(Date codetime) {
		this.codetime = codetime;
	}

	public String getCodetype() {
		return this.codetype;
	}

	public void setCodetype(String codetype) {
		this.codetype = codetype;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}