/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.ddt.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-23-2009
 * 
 * XDoclet definition:
 * @struts.form name="dataForm"
 */
public class HisForm extends ActionForm {
	// Fields

	private String id;
	private String sufferer;
	private String createDate;
	private String hisno;
	private String name;
	private String garden;
	private String old;
	private String ismarry;
	private String height;
	private String weight;
	private String job;
	private String linkman;
	private String relation;
	private String linktel;
	private String gatherDate;
	private String address;
	private String tel;
	private String linkadd;
	private String linkaddrel;
	private String deptid;
	private String hisstate;
	private String cycle;
	private String hislevel;
	private String xregctno;
	private String allergy;
	private String remark;
	private String state;
	private String hisNow;
	private String hisSelf;
	private String hisMarry;
	private String hisFamily;
	private String helpCheckup;
	private String hisSetup;
	private String result;
	private String dispose;
	private String photo;
	private String doctor;
	private String hisDate;
	private String page;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSufferer() {
		return this.sufferer;
	}

	public void setSufferer(String sufferer) {
		this.sufferer = sufferer;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getHisno() {
		return this.hisno;
	}

	public void setHisno(String hisno) {
		this.hisno = hisno;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGarden() {
		return this.garden;
	}

	public void setGarden(String garden) {
		this.garden = garden;
	}

	public String getOld() {
		return this.old;
	}

	public void setOld(String old) {
		this.old = old;
	}

	public String getIsmarry() {
		return this.ismarry;
	}

	public void setIsmarry(String ismarry) {
		this.ismarry = ismarry;
	}

	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public String getLinktel() {
		return this.linktel;
	}

	public void setLinktel(String linktel) {
		this.linktel = linktel;
	}

	public String getGatherDate() {
		return this.gatherDate;
	}

	public void setGatherDate(String gatherDate) {
		this.gatherDate = gatherDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getLinkadd() {
		return this.linkadd;
	}

	public void setLinkadd(String linkadd) {
		this.linkadd = linkadd;
	}

	public String getLinkaddrel() {
		return this.linkaddrel;
	}

	public void setLinkaddrel(String linkaddrel) {
		this.linkaddrel = linkaddrel;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getHisstate() {
		return this.hisstate;
	}

	public void setHisstate(String hisstate) {
		this.hisstate = hisstate;
	}

	public String getCycle() {
		return this.cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle;
	}

	public String getHislevel() {
		return this.hislevel;
	}

	public void setHislevel(String hislevel) {
		this.hislevel = hislevel;
	}

	public String getXregctno() {
		return this.xregctno;
	}

	public void setXregctno(String xregctno) {
		this.xregctno = xregctno;
	}

	public String getAllergy() {
		return this.allergy;
	}

	public void setAllergy(String allergy) {
		this.allergy = allergy;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getHisNow() {
		return this.hisNow;
	}

	public void setHisNow(String hisNow) {
		this.hisNow = hisNow;
	}

	public String getHisSelf() {
		return this.hisSelf;
	}

	public void setHisSelf(String hisSelf) {
		this.hisSelf = hisSelf;
	}

	public String getHisMarry() {
		return this.hisMarry;
	}

	public void setHisMarry(String hisMarry) {
		this.hisMarry = hisMarry;
	}

	public String getHisFamily() {
		return this.hisFamily;
	}

	public void setHisFamily(String hisFamily) {
		this.hisFamily = hisFamily;
	}

	public String getHelpCheckup() {
		return this.helpCheckup;
	}

	public void setHelpCheckup(String helpCheckup) {
		this.helpCheckup = helpCheckup;
	}

	public String getHisSetup() {
		return this.hisSetup;
	}

	public void setHisSetup(String hisSetup) {
		this.hisSetup = hisSetup;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getDispose() {
		return this.dispose;
	}

	public void setDispose(String dispose) {
		this.dispose = dispose;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(String doctor) {
		this.doctor = doctor;
	}

	public String getHisDate() {
		return this.hisDate;
	}

	public void setHisDate(String hisDate) {
		this.hisDate = hisDate;
	}

	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.ismarry="0";
	}

}