package com.crm.group.po;

import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by MyEclipse Persistence Tools
 */

public class Groups implements java.io.Serializable {

	// Fields

	private String groupid;//集团ID

	private String groupname;//集团名称

	private String vocation;//所属行业

	private String grouplevel;//企业级别

	private String privince;//省
	private String city;//市
	private String area;//地区
	private String secity;//页面市
	private String manager;//客户经理
    private String army;//是否党政军
	private String state;//集团状态
	private  String address ;//地址
    private String post; //邮编
    private String useman ;//法人
    private String web ;//网址
    private String openmon ;//注册资金
    private String moneytype ;//财务状况
    private String sendtype ;//营运状况
    private String empcount ;//员工数量
    private String grouptype ;//企业性质
   
  
	// Constructors

	public String getEmpcount() {
		return empcount;
	}

	public void setEmpcount(String empcount) {
		this.empcount = empcount;
	}

	public String getGrouptype() {
		return grouptype;
	}

	public void setGrouptype(String grouptype) {
		this.grouptype = grouptype;
	}

	public String getMoneytype() {
		return moneytype;
	}

	public void setMoneytype(String moneytype) {
		this.moneytype = moneytype;
	}

	public String getOpenmon() {
		return openmon;
	}

	public void setOpenmon(String openmon) {
		this.openmon = openmon;
	}

	public String getSendtype() {
		return sendtype;
	}

	public void setSendtype(String sendtype) {
		this.sendtype = sendtype;
	}

	public String getUseman() {
		return useman;
	}

	public void setUseman(String useman) {
		this.useman = useman;
	}

	public String getWeb() {
		return web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	/** default constructor */
	public Groups() {
	}

	/** full constructor */
	public Groups(String groupname, String vocation, String grouplevel,
			String city,String area,String secity,String privince, String managers,
			String state,String address,String post,String army,
			String useman,String web,String openmon,String moneytype,String sendtype,
			String empcount,String grouptype) {
		this.groupname = groupname;
		this.vocation = vocation;
		this.grouplevel = grouplevel;
		this.city = city;
		this.privince=privince;
		this.manager = managers;
		this.state = state;
		this.address=address;
		this.post=post;
		this.secity=secity;
		this.area=area;
		this.army=army;
		this.useman=useman;
		this.web=web;
		this.openmon=openmon;
		this.moneytype=moneytype;
		this.sendtype=sendtype;
		this.empcount=empcount;
		this.grouptype=grouptype;
	}

	// Property accessors

	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	public String getVocation() {
		return this.vocation;
	}

	public void setVocation(String vocation) {
		this.vocation = vocation;
	}

	public String getGrouplevel() {
		return this.grouplevel;
	}

	public void setGrouplevel(String grouplevel) {
		this.grouplevel = grouplevel;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}



	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPrivince() {
		return privince;
	}

	public void setPrivince(String privince) {
		this.privince = privince;
	}

	

	public String getManager() {
		return manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPost() {
		return post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	

	public String getSecity() {
		return secity;
	}

	public void setSecity(String secity) {
		this.secity = secity;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

public String getArmy() {
		return army;
	}

	public void setArmy(String army) {
		this.army = army;
	}
	

	

}