package com.crm.group.po;

/**
 * VipProvince generated by MyEclipse Persistence Tools
 */

public class VipProvince implements java.io.Serializable {

	// Fields

	private Long NId;

	private String VCode;

	private String VName;

	// Constructors

	/** default constructor */
	public VipProvince() {
	}

	/** full constructor */
	public VipProvince(String VCode, String VName) {
		this.VCode = VCode;
		this.VName = VName;
	}

	// Property accessors

	public Long getNId() {
		return this.NId;
	}

	public void setNId(Long NId) {
		this.NId = NId;
	}

	public String getVCode() {
		return this.VCode;
	}

	public void setVCode(String VCode) {
		this.VCode = VCode;
	}

	public String getVName() {
		return this.VName;
	}

	public void setVName(String VName) {
		this.VName = VName;
	}

}