/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.pub.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-23-2009
 * 
 * XDoclet definition:
 * @struts.form name="dataForm"
 */
public class DataForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** temp property */
	private String temp;

	/** pid property */
	private String pid;

	/** dataName property */
	private String dataName;
	
	private String id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the temp.
	 * @return String
	 */
	public String getTemp() {
		return temp;
	}

	/** 
	 * Set the temp.
	 * @param temp The temp to set
	 */
	public void setTemp(String temp) {
		this.temp = temp;
	}

	/** 
	 * Returns the pid.
	 * @return String
	 */
	public String getPid() {
		return pid;
	}

	/** 
	 * Set the pid.
	 * @param pid The pid to set
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/** 
	 * Returns the dataName.
	 * @return String
	 */
	public String getDataName() {
		return dataName;
	}

	/** 
	 * Set the dataName.
	 * @param dataName The dataName to set
	 */
	public void setDataName(String dataName) {
		this.dataName = dataName;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
}