package com.crm.client.po;

import java.util.HashSet;
import java.util.Set;

/**
 * TClientrule generated by MyEclipse Persistence Tools
 */

public class TClientrule implements java.io.Serializable {

	// Fields

	private Long id;

	private String rulename;

	private Long brand;

	private Long base;

	private String description;

	private String islock;

	private Long pri;

	private Set<TRuleexp> ruleExps = new HashSet<TRuleexp>();

	// Constructors

	/** default constructor */
	public TClientrule() {
	}

	/** full constructor */
	public TClientrule(String rulename, Long brand, Long base,
			String description, String islock, Long pri) {
		this.rulename = rulename;
		this.brand = brand;
		this.base = base;
		this.description = description;
		this.islock = islock;
		this.pri = pri;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRulename() {
		return this.rulename;
	}

	public void setRulename(String rulename) {
		this.rulename = rulename;
	}

	public Long getBrand() {
		return this.brand;
	}

	public void setBrand(Long brand) {
		this.brand = brand;
	}

	public Long getBase() {
		return this.base;
	}

	public void setBase(Long base) {
		this.base = base;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getIslock() {
		return this.islock;
	}

	public void setIslock(String islock) {
		this.islock = islock;
	}

	

	public Set<TRuleexp> getRuleExps() {
		return ruleExps;
	}

	public void setRuleExps(Set<TRuleexp> ruleExps) {
		this.ruleExps = ruleExps;
	}

	public Long getPri() {
		return pri;
	}

	public void setPri(Long pri) {
		this.pri = pri;
	}

}