document.writeln("	<div class=\"copy\"> ");
document.writeln("	<p><a target=\"_blank\" href=\"http:\/\/www.itrust.org.cn\/yz\/pjwx.asp?wm=1553122470\">");
document.writeln("	<img src=\"http:\/\/www.dns65.com\/images\/f-logo.jpg\" width=\"70\" height=\"70\" \/><\/a><\/p>");
document.writeln("	<div class=\"us\">	");
document.writeln("		<div class=\"us_top\">");
document.writeln("			<a href=\"http:\/\/www.dns65.com\/about\/\">关于我们<\/a><span>\|<\/span>");
document.writeln("			<a href=\"http:\/\/www.dns65.com\/customers\/\">典型客户<\/a><span>|<\/span>");
document.writeln("			<a href=\"http:\/\/www.dns65.com\/cooperation\/\">合作伙伴<\/a><span>\|<\/span>");
document.writeln("			<a href=\"http:\/\/www.dns65.com\/IDC\/\">机房介绍<\/a><span>|<\/span>");
document.writeln("		    <a href=\"http:\/\/www.dns65.com\/contact\/\">联系方式<\/a><\/div>");
document.writeln("		<div class=\"us_bottom\">");
document.writeln("			<font>Copyright &copy;2006-2011 DNS65.COM All rights reserved ");
document.writeln("			<a target=\"_blank\" href=\"http:\/\/www.dns65.com\/images\/dns65zz.jpg\" style=\"text-decoration: none\">");
document.writeln("	北京国网华通科技有限公司<\/a>");
document.writeln("			&nbsp;&nbsp;北京市公安局备案编号：110105006757<br\/>");
document.writeln("			地址(ADD)：北京市中关村大街27号中关村大厦1307室&nbsp;增值电信业务经营许可证：");
document.writeln("	<a target=\"_blank\" href=\"http:\/\/www.dns65.com\/images\/dns65icp.jpg\">京ICP证100326号<\/a>&nbsp; ");
document.writeln("	<a href=\"http:\/\/www.miibeian.gov.cn\/\" target=\"_blank\" class=\"t12hei\">京ICP备10023308号<\/a><br\/>");
document.writeln("			服务器租用/托管：010-52722337/39/85/90/96&nbsp; 域名空间：010-52722311/21/25/31&nbsp; 技术电话：010-52722365&nbsp;");
document.writeln("			传真(FAX)：010-52722333	<\/font>");
document.writeln("			<\/div><\/div><\/div>");
