document.writeln("			<div class=\"qkf\">");
document.writeln("				<!--IDC部-->");
document.writeln("				<p class=\"t12-he\" style=\"margin-left:5px;margin-bottom:5px; margin-top:10px;\">IDC和VPS部<\/p>");
document.writeln("					<ul>");
document.writeln("						<li class=\"qqhei\" style=\"margin-top:5px;\">");
document.writeln("	<a class=\"qqhei\" href=\"tencent:\/\/message\/?uin=1203180200&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-风语[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1203180200:17\" align=\"middle\" border=\"0\" \/>]<\/a>");
document.writeln("	<a class=\"qqhei\"  href=\"tencent:\/\/message\/?uin=1252232833&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-田野[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1252232833:17\" align=\"middle\" border=\"0\" \/>]<\/a><\/li>");
document.writeln("						<li class=\"qqhei\" style=\"margin-top:5px;\">");
document.writeln("	<a class=\"qqhei\" href=\"tencent:\/\/message\/?uin=1223972055&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-风帆[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1223972055:17\" align=\"middle\" border=\"0\" \/>]<\/a>");
document.writeln("	<a class=\"qqhei\"  href=\"tencent:\/\/message\/?uin=1195837336&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-小冬[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1195837336:17\" align=\"middle\" border=\"0\" \/>]<\/a><\/li>");
document.writeln("						<li class=\"qqhei\" style=\"margin-top:5px;\">");
document.writeln("	<a class=\"qqhei\" href=\"tencent:\/\/message\/?uin=1206321308&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-小波[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1206321308:17\" align=\"middle\" border=\"0\" \/>]<\/a>");
document.writeln("	<a class=\"qqhei\"  href=\"tencent:\/\/message\/?uin=1095885022&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-行者[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1095885022:17\" align=\"middle\" border=\"0\" \/>]<\/a><\/li>");
document.writeln("						<li class=\"qqhei\" style=\"margin-top:5px;\">");
document.writeln("	<a class=\"qqhei\" href=\"tencent:\/\/message\/?uin=1532397230&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-一品[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1532397230:17\" align=\"middle\" border=\"0\" \/>]<\/a>");
document.writeln("	<a class=\"qqhei\"  href=\"tencent:\/\/message\/?uin=1610372001&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-九品[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1610372001:17\" align=\"middle\" border=\"0\" \/>]<\/a><\/li>");
document.writeln("						<\/ul>");
document.writeln("				<!--IDC部-->");
document.writeln("				<!--虚拟主机-->");
document.writeln("				<p class=\"t12-he\" style=\"margin-left:5px;margin-bottom:5px; margin-top:5px;\">域名空间部<\/p>");
document.writeln("					<ul>");
document.writeln("						<li class=\"qqhei\" style=\"margin-top:5px;\">");
document.writeln("	<a class=\"qqhei\" href=\"tencent:\/\/message\/?uin=1193919328&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-小梅[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1193919328:17\" align=\"middle\" border=\"0\" \/>]<\/a>");
document.writeln("	<a class=\"qqhei\"  href=\"tencent:\/\/message\/?uin=1397925536&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-听雨[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1397925536:17\" align=\"middle\" border=\"0\" \/>]<\/a><\/li>");
document.writeln("						<li class=\"qqhei\" style=\"margin-top:5px;\">");
document.writeln("	<a class=\"qqhei\" href=\"tencent:\/\/message\/?uin=1308505350&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-希望[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1308505350:17\" align=\"middle\" border=\"0\" \/>]<\/a>");
document.writeln("	<a class=\"qqhei\"  href=\"tencent:\/\/message\/?uin=1303771972&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-原味[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1303771972:17\" align=\"middle\" border=\"0\" \/>]<\/a><\/li>");
document.writeln("						<\/ul>");
document.writeln("				<!--虚拟主机-->");
document.writeln("				<!--技术部-->");
document.writeln("				<p class=\"t12-he\" style=\"margin-left:10px; margin-top:5px; margin-bottom: 5px;\">技术支持<\/p>");
document.writeln("					<ul>");
document.writeln("						<li class=\"qqhei\" style=\"margin-top:5px;\">");
document.writeln("	<a class=\"qqhei\" href=\"tencent:\/\/message\/?uin=1301662520&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	华通-技术[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1301662520:17\" align=\"middle\" border=\"0\" \/>]<\/a>");
document.writeln("	<a class=\"qqhei\"  href=\"tencent:\/\/message\/?uin=1335800680&Site=http:\/\/dns65.com&Menu=yes\" target=\"_blank\">");
document.writeln("	备案专员[<img height=\"17\" src=\"http:\/\/wpa.qq.com\/pa?p=1:1335800680:17\" align=\"middle\" border=\"0\" \/>]<\/a><\/li>");
document.writeln("						<\/ul>");
document.writeln("				<!--技术部-->");
document.writeln("			<\/div>")