/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.report.struts.action;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.crm.page.PageUtil;
import com.crm.per.dao.Permission;
import com.crm.pub.GlobVar;
import com.crm.pub.PowerKey;
import com.crm.report.service.dao.RegisterReportServiceDao;
import com.crm.report.struts.bean.RegisterAmountBean;
import com.crm.report.struts.form.RegisterReportForm;

/**
 * 门诊报表 MyEclipse Struts Creation date: 10-15-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/registerReport" name="registerReportForm"
 *                scope="request" validate="true"
 */
public class RegisterReportAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private RegisterReportServiceDao registServiceDao;
	private Permission perDao;

	public Permission getPerDao() {
		return perDao;
	}

	public void setPerDao(Permission perDao) {
		this.perDao = perDao;
	}

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	// public ActionForward execute(ActionMapping mapping, ActionForm form,
	// HttpServletRequest request, HttpServletResponse response) {
	// RegisterReportForm registerReportForm = (RegisterReportForm) form;// TODO
	// Auto-generated method stub
	// return null;
	// }
	public RegisterReportServiceDao getRegistServiceDao() {
		return registServiceDao;
	}

	public void setRegistServiceDao(RegisterReportServiceDao registServiceDao) {
		this.registServiceDao = registServiceDao;
	}

	/**
	 * 门诊汇总报表
	 * 
	 * @throws InvocationTargetException
	 * @throws IllegalAccessException
	 */
	public ActionForward regAmount(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IllegalAccessException, InvocationTargetException {

		RegisterReportForm registerReportForm = (RegisterReportForm) form;
		RegisterAmountBean registerAmountBean = new RegisterAmountBean();
		BeanUtils.copyProperties(registerAmountBean, registerReportForm);

		PageUtil pageUtil = new PageUtil(request, 1,
				GlobVar.PAGESIZE_BY_TEN_DATA);
		List list = registServiceDao.registerAmount(registerAmountBean);

		request.setAttribute("regList", list);
		request.setAttribute("pageUtil", pageUtil);

		// 129角色
		List sl = perDao.getSonPerList(PowerKey.KEY_REGAMOUNT);
		return new ActionForward("/admin/report/register/regAmount.jsp");
	}

	/**
	 * 门诊明细
	 */
	public ActionForward regDetails(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			request.getRequestDispatcher("/admin/reg.do?task=regList").forward(
					request, response);
		} catch (ServletException se) {
			se.printStackTrace();
		} catch (IOException ioe) {
			ioe.printStackTrace();
		}
		return null;
	}
}