/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.crm.score.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/**
 * MyEclipse Struts Creation date: 10-26-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="presentForm"
 */
public class PresentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** num property */
	private String num;

	/** picture property */
	private FormFile pic;

	/** ptype property */
	private String ptype;

	/** indate property */
	private String indate;

	/** integral property */
	private String integral;

	/** name property */
	private String name;

	/** id property */
	private String id;

	/** del property */
	private String del;

	private String sadate;// 起始时间

	private String endate;// 终止时间

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {

		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.del = "0";
	}

	/**
	 * Returns the num.
	 * 
	 * @return String
	 */
	public String getNum() {
		return num;
	}

	/**
	 * Set the num.
	 * 
	 * @param num
	 *            The num to set
	 */
	public void setNum(String num) {
		this.num = num;
	}

	/**
	 * Returns the ptype.
	 * 
	 * @return String
	 */
	public String getPtype() {
		return ptype;
	}

	/**
	 * Set the ptype.
	 * 
	 * @param ptype
	 *            The ptype to set
	 */
	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	/**
	 * Returns the indate.
	 * 
	 * @return String
	 */
	public String getIndate() {
		return indate;
	}

	/**
	 * Set the indate.
	 * 
	 * @param indate
	 *            The indate to set
	 */
	public void setIndate(String indate) {
		this.indate = indate;
	}

	/**
	 * Returns the integral.
	 * 
	 * @return String
	 */
	public String getIntegral() {
		return integral;
	}

	/**
	 * Set the integral.
	 * 
	 * @param integral
	 *            The integral to set
	 */
	public void setIntegral(String integral) {
		this.integral = integral;
	}

	/**
	 * Returns the name.
	 * 
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Returns the id.
	 * 
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Returns the del.
	 * 
	 * @return String
	 */
	public String getDel() {
		return del;
	}

	/**
	 * Set the del.
	 * 
	 * @param del
	 *            The del to set
	 */
	public void setDel(String del) {
		this.del = del;
	}

	public FormFile getPic() {
		return pic;
	}

	public void setPic(FormFile pic) {
		this.pic = pic;
	}

	public String getEndate() {
		return endate;
	}

	public void setEndate(String endate) {
		this.endate = endate;
	}

	public String getSadate() {
		return sadate;
	}

	public void setSadate(String sadate) {
		this.sadate = sadate;
	}

}