<?php
$lang = array(
	"zh_cn"=>array(
		"public"=>array(
			"SiteAddress"=>"您现在的位置",
			"ComparyName"=>"深圳市琢典标识有限公司",
			"AboutUs"=>"关于琢典",
			"Culture"=>"公司文化",
			"LeadWord"=>"领导致辞",
			"EnterpriseHistory"=>"发展历程",
			"News"=>"新闻中心",
			"Author"=>"作者",
			"NewsTime"=>"发布于",
			"NewsSize"=>"字体",
			"NewsSize_L"=>"大",
			"NewsSize_M"=>"中",
			"NewsSize_S"=>"小",
			"PleaseChoose"=>"请选择",
			"Product"=>"产品中心",
			"Case"=>"成功案例",
			"ProductTime"=>"发布时间",
			"JobList"=>"诚聘英才",
			"JobPosition"=>"招聘职位",
			"JobWorkAdd"=>"工作地点",
			"JobCnt"=>"招聘人数",
			"JobInfo"=>"详情",
			"ContactUs"=>"联系方式",
			"Message"=>"信息反馈",
			"Advise"=>"投诉建议"
		),
		"job"=>array(
			"Position"=>"职位名称",
			"PositionType"=>"职位类型",
			"WorkExperience"=>"工作经验",
			"Degree"=>"学历要求",
			"Number"=>"招聘人数",
			"CreateTime"=>"发布时间",
			"JobDesc"=>"职位描述",
			"Requirement"=>"招聘要求",
			"LinkMan"=>"联系人",
			"LinkTelephone"=>"联系电话",
			"LinkEmail"=>"电子邮箱",
			"Apply"=>"职位申请",
			"Name"=>"姓名",
			"Gender"=>"性别",//性别
			"Gender_Male"=>"男",//性别
			"Gender_Female"=>"女",//性别
			"Birthdate"=>"出生日期",
			"MaritalStatus"=>"婚姻状况",
			"MaritalStatus_Nnmarried"=>"未婚",
			"MaritalStatus_Married"=>"已婚",
			"GraduateSchool"=>"毕业院校",
			"HighestDegree"=>"最高学历",
			"GraduationTime"=>"毕业时间",
			"GraduationProfessional"=>"毕业专业",
			"Telephone"=>"联系电话",
			"Mobile"=>"手机号码",
			"Address"=>"通信地址",
			"Email"=>"电子邮箱",
			"Expertise"=>"专业特长",
			"EducationExperience"=>"教育经历",
			"WorkExperience"=>"工作经历",
			"VerificationCode"=>"验证码",
			"Replacement"=>"看不清楚,换一张."
		),
		"message"=>array(
			"Title"=>"留言主题",
			"Content"=>"留言内容",
			"CustomerName"=>"客户名称",
			"LinkMan"=>"联系人",
			"Telephone"=>"联系电话",
			"MSN"=>"QQ/MSN",
			"VerificationCode"=>"验证码",
			"Replacement"=>"看不清楚,换一张.",
			"AdviseContent"=>"投诉建议",
			"YourName"=>"您的姓名",
			"Address"=>"联系地址"
		),
		"product"=>array(
			"BianHao"=>"产品编号",
			"JiaGe"=>"价格",
			"VIPJiaGe"=>"会员价格",
			"ChaKanDaTu"=>"查看大图",
			"ChanPinJieShao"=>"产品简介",
			"ShiYongFangFa"=>"使用方法",
			"ChengFen"=>"产品成分",
			"TiShi"=>"这种观点未经美国食品及药物管理局认可。勿将本产品拿来诊断,治疗或预防疾病。",
		),
	),
	"en"=>array(
		"public"=>array(
			"SiteAddress"=>"Site Add",
			"ComparyName"=>"ShenZhen ZhuoDian Co,ltd.",
			"AboutUs"=>"About ZhuoDian",
			"Culture"=>"Culture",
			"LeadWord"=>"Lead Word",
			"EnterpriseHistory"=>"Enterprise History",
			"News"=>"News",
			"Author"=>"Author",
			"NewsTime"=>"Create Date",
			"NewsSize"=>"FontSize",
			"NewsSize_L"=>"L",
			"NewsSize_M"=>"M",
			"NewsSize_S"=>"S",
			"PleaseChoose"=>"Please Choose",
			"Product"=>"Product",
			"Case"=>"Case",
			"ProductTime"=>"Product Date",
			"JobList"=>"Join Us",
			"JobPosition"=>"Job Position",
			"JobWorkAdd"=>"Work Add",
			"JobCnt"=>"Number",
			"JobInfo"=>"Info",
			"ContactUs"=>"Contact Us",
			"Message"=>"FeedBack",
			"Advise"=>"Advise"
		),
		"job"=>array(
			"Position"=>"Position",//职位名称
			"PositionType"=>"Position Type",
			"WorkExperience"=>"Work Experience",
			"Degree"=>"Degree",
			"Number"=>"Number",
			"CreateTime"=>"Create Date",
			"JobDesc"=>"Job Descriptions",
			"Requirement"=>"Requirement",
			"LinkMan"=>"Link Man",
			"LinkTelephone"=>"Telephone",
			"LinkEmail"=>"E-Mail",
			"Apply"=>"Apply This Job",
			"Name"=>"Name",
			"Gender"=>"Gender",//性别
			"Gender_Male"=>"Male",//性别
			"Gender_Female"=>"Female",//性别
			"Birthdate"=>"Birthdate",
			"MaritalStatus"=>"Marital Status",
			"MaritalStatus_Nnmarried"=>"Nnmarried",
			"MaritalStatus_Married"=>"Married",
			"GraduateSchool"=>"Graduate School",
			"HighestDegree"=>"Highest Degree",
			"GraduationTime"=>"Graduation Time",
			"GraduationProfessional"=>"Graduation Professional",
			"Telephone"=>"Telephone",
			"Mobile"=>"Mobile Phone",
			"Address"=>"Address",
			"Email"=>"E-Mail",
			"Expertise"=>"Expertise",
			"EducationExperience"=>"Education Experience",
			"WorkExperience"=>"Work Experience",
			"VerificationCode"=>"Verification Code",
			"Replacement"=>"Can't see, a replacement."
		),
		"message"=>array(
			"Title"=>"Title",
			"Content"=>"Content",
			"CustomerName"=>"Customer Name",
			"LinkMan"=>"Link Man",
			"Telephone"=>"Telephone",
			"MSN"=>"QQ/MSN",
			"VerificationCode"=>"Verification Code",
			"Replacement"=>"Can't see, a replacement.",
			"AdviseContent"=>"Advise Content",
			"YourName"=>"Your Name",
			"Address"=>"Address"
		),
		"product"=>array(
			"BianHao"=>"Item No",
			"JiaGe"=>"Preferred Customer Price",
			"VIPJiaGe"=>"Customer Price",
			"ChaKanDaTu"=>"View Larger",
			"ChanPinJieShao"=>"Overview",
			"ShiYongFangFa"=>"How To Use",
			"ChengFen"=>"Ingredients",
			"TiShi"=>"This statement has not been evaluated by the Food and Drug Administration. This product is not intended to diagnose, treat, cure or prevent disease. ",
		),
	),
);
session_start();
$currlang = "".$_SESSION["Lang"];
//print_r($currlang);
if(empty($currlang) || ""==$currlang){
	$currlang="zh_cn";
}

?>
