package com.crm.pub.po;

import java.util.HashSet;
import java.util.Set;

/**
 * TRole generated by MyEclipse Persistence Tools
 */

public class TRole implements java.io.Serializable {

	// Fields

	private Long roleid;

	private String rolename;

	private String descript;
	
	private Set<TUser> users = new HashSet<TUser>();
	
	private Set<TPower> powers = new HashSet<TPower>();

	// Constructors

	/** default constructor */
	public TRole() {
	}

	/** full constructor */
	public TRole(String rolename, String descript) {
		this.rolename = rolename;
		this.descript = descript;
	}

	// Property accessors

	public Long getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Long roleid) {
		this.roleid = roleid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	public Set<TUser> getUsers() {
		return users;
	}

	public void setUsers(Set<TUser> users) {
		this.users = users;
	}

	public Set<TPower> getPowers() {
		return powers;
	}

	public void setPowers(Set<TPower> powers) {
		this.powers = powers;
	}

}